src/KairosWeb_Groep6/Models/KairosViewModels/AnalyseViewModel.cs
using KairosWeb_Groep6.Models.Domain;

namespace KairosWeb_Groep6.Models.KairosViewModels
{
    public class AnalyseViewModel
    {
        #region Properties
        public int AnalyseId { get; set; }

        public string Departement { get; set; }

        public string Werkgever { get; set; }

        public string Gemeente { get; set; }

        public decimal KostenTotaal { get; set; }

        public decimal BatenTotaal { get; set; }

        public decimal NettoResultaat { get; set; }

        public bool InArchief { get; set; }

        public decimal KostenPercent { get; set; }

        public decimal BatenPercent { get; set; }

        public string KlasseTotaal { get; set; } // klasse die de kleur van het nettores aangeeft
        #endregion

        #region Constructors
        public AnalyseViewModel()
        {

        }

        public AnalyseViewModel(Analyse analyse)
        {
            AnalyseId = analyse.AnalyseId;

            InArchief = analyse.InArchief;

            if(analyse.Departement != null)
            {
                Departement = analyse.Departement.Naam;
                Werkgever = analyse.Departement.Werkgever.Naam;
                Gemeente = analyse.Departement.Werkgever.Gemeente;
            }
            else
            {
                Werkgever = "Onbekend";
                Departement = "Onbekend";
            }

            KostenTotaal = analyse.KostenTotaal;

            BatenTotaal = analyse.BatenTotaal;

            NettoResultaat = BatenTotaal - KostenTotaal;

            if (BatenTotaal != 0 || KostenTotaal != 0)
            {
                BatenPercent = (BatenTotaal / (BatenTotaal + KostenTotaal)) * 100;
                KostenPercent = (KostenTotaal / (BatenTotaal + KostenTotaal)) * 100;
            }
            else
            {
                BatenPercent = 0;
                KostenPercent = 0;
            }

            // kleur voor nettoresultaat bepalen
            if (NettoResultaat < 0)
            {
                KlasseTotaal = "alert-danger";
            }
            else if (NettoResultaat > 0)
            {
                KlasseTotaal = "alert-success";
            }
            else
            {
                KlasseTotaal = "alert-warning";
            }
        }
        #endregion
    }
}

src/KairosWeb_Groep6/Controllers/AnalyseController.cs
using System;
using System.Linq;
using KairosWeb_Groep6.Filters;
using KairosWeb_Groep6.Models.Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace KairosWeb_Groep6.Controllers
{
    [Authorize]
    [AutoValidateAntiforgeryToken]
    public class AnalyseController : Controller
    {
        #region Properties
        private readonly IAnalyseRepository _analyseRepository;
        private readonly IJobcoachRepository _jobcoachRepository;
        private readonly IExceptionLogRepository _exceptionLogRepository;
        #endregion

        #region Constructors
        public AnalyseController(
            IAnalyseRepository analyseRepository,
            IJobcoachRepository jobcoachRepository,
            IExceptionLogRepository exceptionLogRepository)
        {
            _analyseRepository = analyseRepository;
            _jobcoachRepository = jobcoachRepository;
            _exceptionLogRepository = exceptionLogRepository;
        }
        #endregion

        #region NieuweAnalyse
        [ServiceFilter(typeof(JobcoachFilter))]
        public IActionResult NieuweAnalyse(Jobcoach jobcoach)
        {
            try
            {
                Analyse analyse = new Analyse();

                _analyseRepository.Add(analyse);
                _analyseRepository.Save();

                if (jobcoach != null)
                {
                    jobcoach = _jobcoachRepository.GetById(jobcoach.PersoonId);
                    jobcoach.Analyses.Add(analyse);
                    _jobcoachRepository.Save();

                    if (HttpContext != null)
                    {// nodig voor testen, HttpContext kan je niet mocken
                        AnalyseFilter.SetAnalyseInSession(HttpContext, analyse);
                    }

                    return RedirectToAction("SelecteerWerkgever", "Werkgever");
                }
            }
            catch (Exception e)
            {
                _exceptionLogRepository.Add(new ExceptionLog(e, "Analyse", "NieuweAnalyse"));
                _exceptionLogRepository.Save();
                TempData["error"] = "Er ging iets fout tijdens het starten van een nieuwe analyse, probeer later opnieuw";
            }

            return RedirectToAction("Index", "Kairos");
        }
        #endregion

        #region OpenAnalyse
        [ServiceFilter(typeof(JobcoachFilter))]
        public IActionResult OpenAnalyse(Jobcoach jobcoach, int id)
        {
            try
            {
                // eerst kijken of deze analyse wel van deze jobcoach is
                Analyse mogelijkeAnalyse = jobcoach.Analyses.SingleOrDefault(a => a.AnalyseId == id);

                if (mogelijkeAnalyse == null || mogelijkeAnalyse.Verwijderd)
                {
                    TempData["error"] = "U heeft geen toegang tot deze analyse! Open enkel analyses die u ziet " +
                                        "op de homepagina of in het archief.";
                }
                else
                {
                    Analyse analyse = _analyseRepository.GetByIdAll(id);

                    if (HttpContext != null)
                    {
                        // nodig voor testen, HttpContext kan je niet mocken
                        // analyse instellen in Session
                        AnalyseFilter.SetAnalyseInSession(HttpContext, analyse);
                    }

                    return RedirectToAction("Index", "Resultaat");
                }
            }
            catch (Exception e)
            {
                _exceptionLogRepository.Add(new ExceptionLog(e, "Analyse", "OpenAnalyse"));
                _exceptionLogRepository.Save();
                TempData["error"] = "Er ging iets fout tijdens het ophalen van de analyse, probeer later opnieuw";
            }

            return RedirectToAction("Index", "Kairos");
        }
        #endregion

        #region VerwijderAnalyse
        [ServiceFilter(typeof(JobcoachFilter))]
        public IActionResult VerwijderAnalyse(Jobcoach jobcoach, int id, string from)
        {
            try
            {
                // eerst kijken of deze analyse wel van deze jobcoach is
                Analyse mogelijkeAnalyse = jobcoach.Analyses.SingleOrDefault(a => a.AnalyseId == id);

                if (mogelijkeAnalyse == null || mogelijkeAnalyse.Verwijderd)
                {
                    TempData["error"] = "U heeft geen toegang tot deze analyse! Verwijder enkel analyses die u ziet " +
                                        "op de homepagina of in het archief.";
                }
                else
                {
                    Analyse analyse = _analyseRepository.GetById(id);

                    if (analyse != null)
                    {
                        ViewData["analyseId"] = id;

                        if (analyse.Departement != null)
                        {
                            ViewData["werkgever"] = $"{analyse.Departement.Werkgever.Naam} - {analyse.Departement.Naam}";
                        }

                        ViewData["returnUrl"] = from;

                        return View();
                    }
                }
            }
            catch (Exception e)
            {
                _exceptionLogRepository.Add(new ExceptionLog(e, "Analyse", "VerwijderAnalyse"));
                _exceptionLogRepository.Save();
                TempData["error"] =
                    "Er ging iets fout tijdens het voorbereiden van het verwijderen, probeer later opnieuw";
            }

            return RedirectToAction("Index", "Kairos");
        }

        [HttpPost]
        [ActionName("VerwijderAnalyse")]
        [ServiceFilter(typeof(JobcoachFilter))]
        public IActionResult VerwijderAnalyseBevestigd(Jobcoach jobcoach, int id)
        {
            try
            {
                // eerst kijken of deze analyse wel van deze jobcoach is
                Analyse mogelijkeAnalyse = jobcoach.Analyses.SingleOrDefault(a => a.AnalyseId == id);

                if (mogelijkeAnalyse == null || mogelijkeAnalyse.Verwijderd)
                {
                    TempData["error"] = "U heeft geen toegang tot deze analyse! Verwijderd enkel analyses die u ziet " +
                                        "op de homepagina of in het archief.";
                }
                else
                {
                    Analyse analyse = _analyseRepository.GetById(id);

                    if (analyse != null)
                    {
                        analyse.Verwijderd = true;

                        _analyseRepository.Save();

                        if (analyse.Departement == null)
                        {
                            TempData["message"] = "De analyse is succesvol verwijderd.";
                        }
                        else
                        {
                            TempData["message"] = $"De analyse van {analyse.Departement.Werkgever.Naam} - {analyse.Departement.Naam}" +
                                                  " is succesvol verwijderd.";
                        }
                    }
                }
            }
            catch (Exception e)
            {
                _exceptionLogRepository.Add(new ExceptionLog(e, "Analyse", "VerwijderAnalyseBevestigd"));
                _exceptionLogRepository.Save();
                TempData["error"] = "Er ging onverwachts iets fout, probeer later opnieuw.";
            }

            return RedirectToAction("Index", "Kairos");
        }
        #endregion

        #region Archiveer
        [ServiceFilter(typeof(JobcoachFilter))]
        public IActionResult Archiveer(Jobcoach jobcoach, int id)
        {
            try
            {
                // eerst kijken of deze analyse wel van deze jobcoach is
                Analyse mogelijkeAnalyse = jobcoach.Analyses.SingleOrDefault(a => a.AnalyseId == id);

                if (mogelijkeAnalyse == null || mogelijkeAnalyse.Verwijderd)
                {
                    TempData["error"] = "U heeft geen toegang tot deze analyse! Open enkel analyses die u ziet " +
                                        "op de homepagina of in het archief.";
                }
                else
                {
                    ViewData["analyseId"] = id;
                    Analyse analyse = _analyseRepository.GetById(id);

                    if (analyse.Departement != null)
                    {
                        ViewData["werkgever"] = $"{analyse.Departement.Werkgever.Naam} - {analyse.Departement.Naam}";
                    }

                    return View("ArchiveerAnalyse");
                }
            }
            catch (Exception e)
            {
                _exceptionLogRepository.Add(new ExceptionLog(e, "Analyse", "Archiveer"));
                _exceptionLogRepository.Save();
                TempData["error"] = "Er ging iets fout tijdens het ophalen van de analyse, probeer later opnieuw";
            }

            return RedirectToAction("Index", "Kairos");
        }

        [HttpPost]
        [ActionName("Archiveer")]
        [ServiceFilter(typeof(JobcoachFilter))]
        public IActionResult ArchiveerBevestigd(Jobcoach jobcoach, int id)
        {
            try
            {
                // eerst kijken of deze analyse wel van deze jobcoach is
                Analyse mogelijkeAnalyse = jobcoach.Analyses.SingleOrDefault(a => a.AnalyseId == id);

                if (mogelijkeAnalyse == null || mogelijkeAnalyse.Verwijderd)
                {
                    TempData["error"] = "U heeft geen toegang tot deze analyse! Open enkel analyses die u ziet " +
                                        "op de homepagina of in het archief.";
                }
                else
                {
                    Analyse analyse = _analyseRepository.GetById(id);

                    if (analyse != null)
                    {

src/KairosWeb_Groep6/Controllers/BatenController.cs
using KairosWeb_Groep6.Filters;
using KairosWeb_Groep6.Models.Domain;
using KairosWeb_Groep6.Models.KairosViewModels.Baten;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace KairosWeb_Groep6.Controllers
{
    [Authorize]
    public class BatenController : Controller
    {
        private readonly IAnalyseRepository _analyseRepository;

        public BatenController(IAnalyseRepository analyseRepository)
        {
            _analyseRepository = analyseRepository;
        }

        [ServiceFilter(typeof(AnalyseFilter))]
        public IActionResult Index(Analyse analyse)
        {
            analyse = _analyseRepository.GetByIdAll(analyse.AnalyseId);
            BatenIndexViewModel model = new BatenIndexViewModel(analyse);

            return View(model);
        }

        public IActionResult MedewerkerZelfdeNiveau()
        {
            return RedirectToAction("Index", "MedewerkersZelfdeNiveau");
        }

        public IActionResult MedewerkerHogerNiveau()
        {
            return RedirectToAction("Index", "MedewerkersHogerNiveau");
        }

        public IActionResult UitzendKrachtBesparingen()
        {
            return RedirectToAction("Index", "UitzendKrachtBesparingen");
        }

        public IActionResult ExtraOmzet()
        {
            return RedirectToAction("Index", "ExtraOmzet");
        }

        public IActionResult ExtraProductiviteit()
        {
            return RedirectToAction("Index", "ExtraProductiviteit");
        }

        public IActionResult OverurenBesparing()
        {
            return RedirectToAction("Index", "OverurenBesparing");
        }

        public IActionResult ExterneInkopen()
        {
            return RedirectToAction("Index", "ExterneInkopen");
        }

        public IActionResult Subsidie()
        {
            return RedirectToAction("Index", "Subsidie");
        }

        public IActionResult LogistiekeBesparing()
        {
            return RedirectToAction("Index", "LogistiekeBesparing");
        }

        public IActionResult ExtraBesparingen()
        {
            return RedirectToAction("Index", "ExtraBesparingen");
        }
    }
}

src/KairosWeb_Groep6/Controllers/KostenController.cs
using KairosWeb_Groep6.Filters;
using KairosWeb_Groep6.Models.Domain;
using Microsoft.AspNetCore.Mvc;
using KairosWeb_Groep6.Models.KairosViewModels.Kosten;
using Microsoft.AspNetCore.Authorization;

namespace KairosWeb_Groep6.Controllers
{
    [Authorize]
    public class KostenController : Controller
    {
        private readonly IAnalyseRepository _analyseRepository;

        public KostenController(IAnalyseRepository analyseRepository)
        {
            _analyseRepository = analyseRepository;
        }

        [ServiceFilter(typeof(AnalyseFilter))]
        public IActionResult Index(Analyse analyse)
        {
            analyse = _analyseRepository.GetByIdAll(analyse.AnalyseId);
            KostenIndexViewModel model = new KostenIndexViewModel(analyse);

            return View(model);
        }

        public IActionResult BegeleidingsKosten()
        {
            return RedirectToAction("Index", "BegeleidingsKosten");
        }

        public IActionResult EnclaveKosten()
        {
            return RedirectToAction("Index", "EnclaveKosten");
        }

        public IActionResult ExtraKosten()
        {
            return RedirectToAction("Index", "ExtraKosten");
        }

        public IActionResult GereedschapsKosten()
        {
            return RedirectToAction("Index", "GereedschapsKosten");
        }

        public IActionResult PersoneelsKosten()
        {
            return RedirectToAction("Index", "PersoneelsKosten");
        }

        public IActionResult Loonkosten()
        {
            return RedirectToAction("Index", "Loonkosten");
        }

        public IActionResult OpleidingsKosten()
        {
            return RedirectToAction("Index", "OpleidingsKosten");
        }

        public IActionResult VoorbereidingsKosten()
        {
            return RedirectToAction("Index", "VoorbereidingsKosten");
        }
    }
}

src/KairosWeb_Groep6/Views/Shared/_AnalyseCard.cshtml
@using System.Globalization
@model KairosWeb_Groep6.Models.KairosViewModels.AnalyseViewModel

<div class="card_wrapper col-sm-12 col-md-6 col-lg-4 animated fadeInUp">
    <div class="card">
        <div>
            <div style="overflow: auto;">
                <!--Overflow omdat anders de border boven de h3 en knop staat-->
                <div class="col-md-6" style="padding-left: 0;">
                    <h3>@Model.Werkgever</h3>
                </div>
                <div class="col-md-6 text-right headerButtons text-right" style="margin-top: 20px; padding-right: 0;">
                    <!--margin omdat de h3 dezelfde margin heeft-->
                    @if (!Model.InArchief)
                    {
                        <a asp-controller="Analyse" asp-action="OpenAnalyse" asp-route-id="@Model.AnalyseId"
                           title="Bewerk deze analyse">
                            <i class="fa fa-pencil" aria-hidden="true"></i> <!-- BEWERKEN -->
                        </a>
                    }

                    @if (Model.InArchief)
                    {
                        <a asp-controller="Archief" asp-action="HaalAnalyseUitArchief" asp-route-id="@Model.AnalyseId"
                           title="Haal deze analyse uit het archief">
                            <i class="fa fa-reply" aria-hidden="true"></i> <!-- UIT ARCHIEF HALEN -->
                        </a>
                    }
                    else
                    {
                        <a asp-controller="Analyse" asp-action="Archiveer" asp-route-id="@Model.AnalyseId"
                           title="Verplaats deze analyse naar het archief">
                            <i class="fa fa-archive" aria-hidden="true"></i> <!-- ARCHIVEREN -->
                        </a>
                    }

                    <a asp-controller="Resultaat" asp-action="MaakExcel" asp-route-id="@Model.AnalyseId"
                       title="Maak een pdf van deze analyse">
                        <i class="fa fa-file-excel-o" aria-hidden="true"></i> <!-- EXCEL MAKEN -->
                    </a>

                    <a asp-controller="Analyse" asp-action="VerwijderAnalyse" asp-route-id="@Model.AnalyseId" asp-route-from="card"
                       title="Verwijder deze analyse">
                        <i class="fa fa-trash" aria-hidden="true"></i> <!-- VERWIJDEREN -->
                    </a>
                </div>
            </div>

            @if (Model.Gemeente != null)
            {
                <p>@Model.Departement - @Model.Gemeente</p>
            }
            else
            {
                <p>@Model.Departement</p>
            }

            <div class="col-xs-12 col-md-12 subTotalen noPadding">
                <div class="col-xs-6  col-md-6 text-left bedragBaat">
                    <b>@Model.BatenTotaal.ToString("C", new CultureInfo("nl-BE"))</b>
                </div>
                <div class=" col-xs-6 col-md-6 text-right bedragKost">
                    <b>@Model.KostenTotaal.ToString("C", new CultureInfo("nl-BE"))</b>
                </div>
            </div>
            <div class="col-xs-12 col-md-12 noPadding">
                <div class="progress">
                    <div class="progress-bar progress-bar-success" role="progressbar" id="subTotaalBaten"
                         style="width: @(Math.Round(Model.BatenPercent, 0))%">


                    </div>

                    <div class="progress-bar progress-bar-danger @Model.BatenTotaal" role="progressbar" id="subTotaalKosten"
                         style="width: @(Math.Round(Model.KostenPercent, 0))%">


                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-md-12 noPadding">
                <div class="text-center resultaat alert @Model.KlasseTotaal">
                    <b>@Model.NettoResultaat.ToString("C", new CultureInfo("nl-BE"))</b>
                </div>
            </div>
        </div>
    </div>
</div>

src/KairosWeb_Groep6/Views/Shared/_AnalyseCardList.cshtml
@using System.Globalization
@model KairosWeb_Groep6.Models.KairosViewModels.AnalyseViewModel

<div class="col-sm-12 col-md-12 col-lg-12">
    <div class="card">
        <div>
            <div style="overflow: auto;">
                <!--Overflow omdat anders de border boven de h3 en knop staat-->
                <div class="col-md-6" style="padding-left: 0;">
                    <h3>@Model.Werkgever</h3>
                </div>
                <div class="col-md-6 text-right headerButtons text-right" style="margin-top: 20px; padding-right: 0;">
                    <!--margin omdat de h3 dezelfde margin heeft-->
                    @if (!Model.InArchief)
                    {
                        <a asp-controller="Analyse" asp-action="OpenAnalyse" asp-route-id="@Model.AnalyseId"
                           title="Bewerk deze analyse">
                            <i class="fa fa-pencil" aria-hidden="true"></i> <!-- BEWERKEN -->
                        </a>
                    }

                    @if (Model.InArchief)
                    {
                        <a asp-controller="Archief" asp-action="HaalAnalyseUitArchief" asp-route-id="@Model.AnalyseId"
                           title="Haal deze analyse uit het archief">
                            <i class="fa fa-reply" aria-hidden="true"></i> <!-- UIT ARCHIEF HALEN -->
                        </a>
                    }
                    else
                    {
                        <a asp-controller="Analyse" asp-action="Archiveer" asp-route-id="@Model.AnalyseId"
                           title="Verplaats deze analyse naar het archief">
                            <i class="fa fa-archive" aria-hidden="true"></i> <!-- ARCHIVEREN -->
                        </a>
                    }

                    <a asp-controller="Resultaat" asp-action="MaakExcel" asp-route-id="@Model.AnalyseId"
                       title="Maak een pdf van deze analyse">
                        <i class="fa fa-file-excel-o" aria-hidden="true"></i> <!-- EXCEL MAKEN -->
                    </a>

                    <a asp-controller="Analyse" asp-action="VerwijderAnalyse" asp-route-id="@Model.AnalyseId" asp-route-from="card"
                       title="Verwijder deze analyse">
                        <i class="fa fa-trash" aria-hidden="true"></i> <!-- VERWIJDEREN -->
                    </a>
                </div>
            </div>

            @if (Model.Gemeente != null)
            {
                <p>@Model.Departement - @Model.Gemeente</p>
            }
            else
            {
                <p>@Model.Departement</p>
            }

            <div class="progress">
                <div class="progress-bar progress-bar-success" role="progressbar"
                     style="width: @(Math.Round(Model.BatenPercent, 0))%">
                </div>
                <div class="progress-bar progress-bar-danger" role="progressbar"
                     style="width: @(Math.Round(Model.KostenPercent, 0))%">
                </div>
            </div>

            <div class="text-center resultaat alert @Model.KlasseTotaal">
                <b>@Model.NettoResultaat.ToString("C", new CultureInfo("nl-BE"))</b>
            </div>
        </div>
    </div>
</div>

src/KairosWeb_Groep6/Views/Shared/_Analyses.cshtml
@using KairosWeb_Groep6.Models.KairosViewModels
@model KairosWeb_Groep6.Models.KairosViewModels.IndexViewModel

@foreach (AnalyseViewModel a in Model.Analyses)
{
    @Html.Partial("_AnalyseCard", a)
}

src/KairosWeb_Groep6/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"]</title>
    <link rel="icon" href="/images/favicon.ico"> <!--Icoon in het tabblad-->

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/font-awesome.css" />
        <link href="https://fonts.googleapis.com/css?family=Asap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
        @RenderSection("styles", false)
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/font-awesome.min.css" />
        <link href="https://fonts.googleapis.com/css?family=Asap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
        @RenderSection("styles", false)
    </environment>
</head>
<body>
@if (TempData["Actie"] == null)
{
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Kairos" asp-action="Index" class="navbar-brand" 
                   data-toggle="tooltip" data-placement="bottom"
                   title="Ga terug naar de homepagina">
                    <img src="/images/logo's/kairos_wordmark_normal.png" alt="Logo Kairos"/>
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li><a asp-area="" asp-controller="Kairos" asp-action="Index"
                               data-toggle="tooltip" data-placement="bottom"
                               title="Ga terug naar de homepagina">
                            <i class="fa fa-home fa-2x" aria-hidden="true"></i>
                            <span class="mobile"> Home</span>
                        </a></li>
                        <li><a asp-area="" asp-controller="Analyse" asp-action="NieuweAnalyse"
                               data-toggle="tooltip" data-placement="bottom"
                               title="Maak een nieuwe analyse">
                            <i class="fa fa-line-chart fa-2x" aria-hidden="true"></i>
                            <span class="mobile"> Nieuwe analyse</span>
                        </a></li>
                        <li><a asp-area="" asp-controller="Archief" asp-action="Index"
                               data-toggle="tooltip" data-placement="bottom"
                               title="Ga naar het archief van de analyses">
                            <i class="fa fa-archive fa-2x" aria-hidden="true"></i>
                            <span class="mobile"> Archief</span>
                        </a></li>
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
}
<div class="container body-content">
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success animated slideInDown">@TempData["message"]</div>
    }
    @if (TempData["error"] != null)
    {
        <div class="alert alert-warning animated rubberBand">@TempData["error"]</div>
    }
    @RenderBody()
    
    @if (TempData["Actie"] == null)
    {
        <hr/>
        <footer class="text-center">
            <p>&copy; 2017 - Kairos</p>
        </footer>
    }
</div>

<environment names="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment names="Staging,Production">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

@RenderSection("scripts", false)
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
</body>
</html>

src/KairosWeb_Groep6/Views/Shared/_Tabs.cshtml
<!--tabs-->
<ul class="nav nav-tabs nav-analyse">
    <li id="werkgever">
        <a asp-controller="Werkgever" asp-action="Index">Werkgever</a>
    </li>
    <li id="contactpersoon">
        <a asp-controller="ContactPersoon" asp-action="Index">Contactpersoon</a>
    </li>
    <li id="kosten">
        <a asp-controller="Kosten" asp-action="Index">Kosten</a>
    </li>
    <li id="baten">
        <a asp-controller="Baten" asp-action="Index">Baten</a>
    </li>
    <li id="resultaat">
        <a asp-controller="Resultaat" asp-action="Index">Resultaat</a>
    </li>
</ul>